[package]
  cjc-version = "1.0.5"
  name = "regex_cli"
  description = "Command-line adapter for cjregex"
  version = "0.3.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  cjregex = { path = "../port" }
