[package]
  cjc-version = "1.0.5"
  name = "cjregex"
  description = "Native Cangjie regex prototype and differential validation CLI"
  version = "0.1.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
