"""Import pinned Unicode binary-property tables and aliases; regenerate offline."""
import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path
from generate_categories import parse_table
from generate_unicode import ROOT, REV, VERSION

SNAPSHOT = ROOT / 'data/unicode/binary_properties.json'
OUTPUT = ROOT / 'port/src/unicode_binary.cj'


def validate(data):
    if data['revision'] != REV or data['unicode_version'] != VERSION:
        raise ValueError('unexpected version')
    if len(data['classes']) != 64 or set(data['aliases'].values()) != set(data['classes']):
        raise ValueError('expected 64 queryable binary properties and their aliases')
    for ranges in data['classes'].values():
        last = -1
        for a, b in ranges:
            if not (0 <= a <= b <= 0x10ffff and a > last) or (a <= 0xdfff and b >= 0xd800):
                raise ValueError('invalid scalar interval')
            last = b


def read_upstream(path):
    if subprocess.check_output(['git', '-C', str(path), 'rev-parse', 'HEAD'], text=True).strip() != REV:
        raise ValueError('wrong upstream revision')
    data = {'revision': REV, 'unicode_version': VERSION, 'sources': {}, 'classes': {}, 'aliases': {}}
    texts = {}
    for name in ['property_bool.rs', 'property_names.rs']:
        file = 'regex-syntax/src/unicode_tables/' + name
        raw = (path / file).read_bytes()
        if raw != subprocess.check_output(['git', '-C', str(path), 'show', REV + ':' + file]):
            raise ValueError('modified upstream source')
        if 'Unicode version: ' + VERSION + '.' not in raw.decode():
            raise ValueError('wrong Unicode version')
        data['sources'][name] = hashlib.sha256(raw).hexdigest()
        texts[name] = raw.decode()
    text = texts['property_bool.rs']
    names = re.findall(r'\("([A-Za-z_0-9]+)", ([A-Z_]+)\),', text.split('];', 1)[0])
    if len(names) != 65:
        raise ValueError('unexpected binary table inventory')
    aliases = {}
    body = texts['property_names.rs'].split('= &[', 1)[1].split('];', 1)[0]
    for line in body.splitlines():
        if not line.strip():
            continue
        match = re.fullmatch(r'\s*\("([a-z0-9]+)", "([A-Za-z_0-9]+)"\),\s*', line)
        if not match:
            raise ValueError('unrecognized property alias: ' + line)
        aliases[match[1]] = match[2]
    unreachable = {name for name, _ in names} - set(aliases.values())
    # Upstream includes InCB data but canonicalizes that query to
    # Indic_Conjunct_Break, which bool_property does not resolve.
    if unreachable != {'InCB'}:
        raise ValueError('unexpected unqueryable binary table')
    data['excluded_tables'] = sorted(unreachable)
    for name, const in names:
        if name not in unreachable:
            data['classes'][name] = parse_table(text, const)
    data['aliases'] = {k: v for k, v in aliases.items() if v in data['classes']}
    validate(data)
    return data


def render(data):
    lines = ['package cjregex', '', '// Generated by scripts/generate_binary.py; do not edit.',
             '// Unicode ' + VERSION + '; source revision ' + REV + '.',
             '// See data/unicode/LICENSE-UNICODE and THIRD_PARTY_NOTICES.md.',
             'func binaryProperty(name: String): Option<CharSet> {', '    match (name) {']
    for name in data['classes']:
        aliases = [k for k, v in data['aliases'].items() if v == name]
        lines.append('        case ' + ' | '.join('"' + a + '"' for a in aliases) + ' => return Some(binary' + name + '())')
    lines += ['        case _ => return None', '    }', '}', '']
    for name, ranges in data['classes'].items():
        lines += ['func binary' + name + '(): CharSet {', '    CharSet([']
        lines += ['        0x%X, 0x%X,' % (a, b) for a, b in ranges]
        lines += ['    ])', '}', '']
    return '\n'.join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--upstream', type=Path)
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    data = read_upstream(args.upstream) if args.upstream else json.loads(SNAPSHOT.read_text())
    validate(data)
    snapshot = json.dumps(data, ensure_ascii=False, indent=2) + '\n'
    output = render(data)
    if args.check:
        if args.upstream and SNAPSHOT.read_text() != snapshot:
            raise ValueError('snapshot differs from upstream')
        if OUTPUT.read_text() != output:
            raise ValueError('generated binary table is stale')
    else:
        if args.upstream:
            SNAPSHOT.write_text(snapshot)
        OUTPUT.write_text(output)
    print('Unicode ' + VERSION + ' binary properties verified: ' + str(len(data['classes'])) + ' tables, ' + str(len(data['aliases'])) + ' aliases')


if __name__ == '__main__':
    main()
