"""Generate Cangjie Perl class tables from a pinned, normalized Unicode snapshot.
Default/--check needs no network or upstream checkout. --upstream PATH rebuilds
that snapshot from the three tables in the pinned Rust checkout.
"""
import argparse
import ast
import hashlib
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
REV = '72d650cb0a880a01ab6dc2137c0888e8f89740f7'
VERSION = '16.0.0'
SNAPSHOT = ROOT / 'data/unicode/perl_classes.json'
OUTPUT = ROOT / 'port/src/unicode_classes.cj'
SOURCES = [('d','perl_decimal.rs'), ('s','perl_space.rs'), ('w','perl_word.rs')]

def validate(data):
    if data['revision'] != REV or data['unicode_version'] != VERSION:
        raise ValueError('unexpected source version')
    if set(data['classes']) != {'d','s','w'}:
        raise ValueError('unexpected class names')
    for ranges in data['classes'].values():
        last = -1
        for low,high in ranges:
            if not (0 <= low <= high <= 0x10ffff and low > last):
                raise ValueError('invalid or overlapping scalar ranges')
            if low <= 0xdfff and high >= 0xd800:
                raise ValueError('surrogate in scalar table')
            last = high

def read_upstream(path):
    if subprocess.check_output(['git','-C',str(path),'rev-parse','HEAD'],text=True).strip() != REV:
        raise ValueError('upstream checkout is not the pinned revision')
    directory = path/'regex-syntax/src/unicode_tables'
    data = {'revision':REV,'unicode_version':VERSION,'sources':{},'classes':{}}
    def rune(token):
        token = re.sub(r'\\u\{([0-9a-fA-F]+)\}', lambda m: '\\U'+format(int(m[1],16),'08x'),token)
        value = ast.literal_eval(token)
        if len(value) != 1: raise ValueError('invalid Rust scalar literal')
        return ord(value)
    literal = r"'(?:\\.|[^'\\])*'"
    for key,filename in SOURCES:
        raw = (directory/filename).read_bytes()
        # Verify the working file against the committed object, not just HEAD.
        committed = subprocess.check_output(['git','-C',str(path),'show',REV+':regex-syntax/src/unicode_tables/'+filename])
        if raw != committed: raise ValueError('modified upstream table: '+filename)
        text = raw.decode()
        if 'Unicode version: '+VERSION+'.' not in text: raise ValueError('unexpected Unicode version')
        body = text.split('= &[',1)[1].split('];',1)[0]
        pairs = []
        for line in body.splitlines():
            if not line.strip(): continue
            pair = re.fullmatch(r'\s*\(('+literal+r'), ('+literal+r')\),\s*',line)
            if not pair: raise ValueError('unrecognized source row: '+line)
            pairs.append(pair.groups())
        if not pairs: raise ValueError('empty source table')
        data['classes'][key] = [[rune(a),rune(b)] for a,b in pairs]
        data['sources'][filename] = hashlib.sha256(raw).hexdigest()
    validate(data)
    return data

def render(data):
    lines = ['package cjregex','', '// Generated by scripts/generate_unicode.py; do not edit.',
             '// Unicode '+VERSION+'; upstream '+REV+'.',
             '// See data/unicode/LICENSE-UNICODE and THIRD_PARTY_NOTICES.md.',
             'func unicodeClass(c: Rune): CharSet {', '    let data: Array<Int64> = match (c) {']
    for key,_ in SOURCES:
        lines.append("        case r'"+key+"' => [")
        for a,b in data['classes'][key]: lines.append('            0x%X, 0x%X,'%(a,b))
        lines.append('        ]')
    lines += ['        case _ => throw Exception("unknown Unicode shorthand class")','    }',
              '    return CharSet(data)','}','']
    return '\n'.join(lines)

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--upstream',type=Path)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    data = read_upstream(args.upstream) if args.upstream else json.loads(SNAPSHOT.read_text())
    validate(data)
    snapshot=json.dumps(data,ensure_ascii=False,indent=2)+'\n'
    generated=render(data)
    if args.check:
        if args.upstream and SNAPSHOT.read_text()!=snapshot: raise ValueError('snapshot differs from upstream')
        if OUTPUT.read_text()!=generated: raise ValueError('generated Cangjie is stale')
    else:
        if args.upstream: SNAPSHOT.write_text(snapshot)
        OUTPUT.write_text(generated)
    print('Unicode '+VERSION+' tables verified: '+', '.join(k+'='+str(len(v))+' ranges' for k,v in data['classes'].items()))
if __name__=='__main__': main()
