"""Import pinned Unicode general categories and aliases, or regenerate offline."""
import argparse
import ast
import hashlib
import json
import re
import subprocess
from pathlib import Path
from generate_unicode import ROOT, REV, VERSION

SNAPSHOT=ROOT/'data/unicode/general_categories.json'
OUTPUT=ROOT/'port/src/unicode_categories.cj'

def validate(data):
    if data['revision']!=REV or data['unicode_version']!=VERSION: raise ValueError('unexpected version')
    if len(data['classes'])!=37: raise ValueError('expected 37 scalar general categories')
    for ranges in data['classes'].values():
        last=-1
        for a,b in ranges:
            if not (0<=a<=b<=0x10ffff and a>last) or (a<=0xdfff and b>=0xd800):
                raise ValueError(('invalid scalar interval',a,b,last))
            last=b
    for value in data['aliases'].values():
        if value not in data['classes'] and value!='Surrogate': raise ValueError('unknown alias target')

def parse_table(text,const):
    literal=r"'(?:\\.|[^'\\])*'"
    def scalar(token):
        token=re.sub(r'\\u\{([0-9a-fA-F]+)\}',lambda m:'\\U'+format(int(m[1],16),'08x'),token)
        s=ast.literal_eval(token)
        if len(s)!=1: raise ValueError('invalid scalar literal')
        return ord(s)
    table=re.search(r'pub const '+re.escape(const)+r':[^=]+=' + r'\s*&\[(.*?)\];',text,re.S)
    if not table: raise ValueError('missing category table: '+const)
    body=table[1]
    ranges=[]
    end=0
    for pair in re.finditer(r'\(('+literal+r'),\s*('+literal+r')\)\s*,?',body):
        if body[end:pair.start()].strip(): raise ValueError('unrecognized category data')
        end=pair.end()
        a,b=scalar(pair[1]),scalar(pair[2])
        # A Rust char interval may bridge the surrogate hole.
        if a<=0xdfff and b>=0xd800:
            if a<0xd800: ranges.append([a,0xd7ff])
            if b>0xdfff: ranges.append([0xe000,b])
        else: ranges.append([a,b])
    if body[end:].strip() or not ranges: raise ValueError('invalid category data')
    return ranges

def read_upstream(path):
    if subprocess.check_output(['git','-C',str(path),'rev-parse','HEAD'],text=True).strip()!=REV:
        raise ValueError('wrong upstream revision')
    data={'revision':REV,'unicode_version':VERSION,'sources':{},'classes':{},'aliases':{}}
    texts={}
    for name in ['general_category.rs','property_values.rs']:
        file='regex-syntax/src/unicode_tables/'+name
        raw=(path/file).read_bytes()
        if raw!=subprocess.check_output(['git','-C',str(path),'show',REV+':'+file]):
            raise ValueError('modified upstream source')
        if 'Unicode version: '+VERSION+'.' not in raw.decode(): raise ValueError('wrong Unicode version')
        data['sources'][name]=hashlib.sha256(raw).hexdigest()
        texts[name]=raw.decode()
    text=texts['general_category.rs']
    names=re.findall(r'\("([A-Za-z_]+)", ([A-Z_]+)\),',text.split('];',1)[0])
    for name,const in names:
        data['classes'][name]=parse_table(text,const)
    body=texts['property_values.rs'].split('"General_Category",',1)[1].split('&[',1)[1].split('],',1)[0]
    for line in body.splitlines():
        if not line.strip(): continue
        match=re.fullmatch(r'\s*\("([a-z]+)", "([A-Za-z_]+)"\),\s*',line)
        if not match: raise ValueError('unrecognized alias: '+line)
        data['aliases'][match[1]]=match[2]
    validate(data)
    return data

def render(data):
    lines=['package cjregex','','// Generated by scripts/generate_categories.py; do not edit.',
           '// Unicode '+VERSION+'; source revision '+REV+'.',
           '// See data/unicode/LICENSE-UNICODE and THIRD_PARTY_NOTICES.md.',
           'func generalCategory(name: String): CharSet {','    match (name) {']
    for name in data['classes']:
        aliases=[k for k,v in data['aliases'].items() if v==name]
        lines.append('        case '+' | '.join('"'+a+'"' for a in aliases)+' => return category'+name+'()')
    lines += ['        case "any" => return CharSet([0, 0xD7FF, 0xE000, 0x10FFFF])',
              '        case "ascii" => return CharSet([0, 127])',
              '        case "assigned" => return categoryUnassigned().negated()',
              '        case _ => throw Exception("unsupported or unknown Unicode general category: " + name)',
              '    }','}','']
    for name,ranges in data['classes'].items():
        lines += ['func category'+name+'(): CharSet {','    CharSet([']
        for a,b in ranges: lines.append('        0x%X, 0x%X,'%(a,b))
        lines += ['    ])','}','']
    return '\n'.join(lines)

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--upstream',type=Path);p.add_argument('--check',action='store_true');args=p.parse_args()
    data=read_upstream(args.upstream) if args.upstream else json.loads(SNAPSHOT.read_text())
    validate(data)
    snapshot=json.dumps(data,ensure_ascii=False,indent=2)+'\n';output=render(data)
    if args.check:
        if args.upstream and SNAPSHOT.read_text()!=snapshot: raise ValueError('snapshot differs from upstream')
        if OUTPUT.read_text()!=output: raise ValueError('generated category table is stale')
    else:
        if args.upstream: SNAPSHOT.write_text(snapshot)
        OUTPUT.write_text(output)
    print('Unicode '+VERSION+' general categories verified: '+str(len(data['classes']))+' tables, '+str(len(data['aliases']))+' aliases')
if __name__=='__main__':main()
