"""Import pinned Unicode Script/Script_Extensions tables; regenerate offline."""
import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path
from generate_categories import parse_table
from generate_unicode import ROOT, REV, VERSION

SNAPSHOT = ROOT / 'data/unicode/scripts.json'
OUTPUT = ROOT / 'port/src/unicode_scripts.cj'
KINDS = {'Script': 'script', 'Script_Extensions': 'script_extension'}


def validate(data):
    if data['revision'] != REV or data['unicode_version'] != VERSION:
        raise ValueError('unexpected version')
    for kind in KINDS:
        tables = data['tables'][kind]
        if len(tables) != 170:
            raise ValueError('expected 170 scripts')
        for ranges in tables.values():
            last = -1
            for a, b in ranges:
                if not (0 <= a <= b <= 0x10ffff and a > last) or (a <= 0xdfff and b >= 0xd800):
                    raise ValueError('invalid scalar interval')
                last = b
        if set(data['aliases'][kind].values()) != set(tables) | {'Unknown', 'Katakana_Or_Hiragana'}:
            raise ValueError('script aliases and tables differ')


def read_upstream(path):
    if subprocess.check_output(['git', '-C', str(path), 'rev-parse', 'HEAD'], text=True).strip() != REV:
        raise ValueError('wrong upstream revision')
    data = {'revision': REV, 'unicode_version': VERSION, 'sources': {}, 'tables': {}, 'aliases': {}}
    texts = {}
    for name in ['script.rs', 'script_extension.rs', 'property_values.rs']:
        file = 'regex-syntax/src/unicode_tables/' + name
        raw = (path / file).read_bytes()
        if raw != subprocess.check_output(['git', '-C', str(path), 'show', REV + ':' + file]):
            raise ValueError('modified upstream source')
        if 'Unicode version: ' + VERSION + '.' not in raw.decode():
            raise ValueError('wrong Unicode version')
        data['sources'][name] = hashlib.sha256(raw).hexdigest()
        texts[name] = raw.decode()
    for kind, source in KINDS.items():
        text = texts[source + '.rs']
        names = re.findall(r'\("([A-Za-z_]+)", ([A-Z_]+)\),', text.split('];', 1)[0])
        data['tables'][kind] = {name: parse_table(text, const) for name, const in names}
        body = texts['property_values.rs'].split('"' + kind + '",', 1)[1].split('&[', 1)[1].split('],', 1)[0]
        aliases = {}
        for line in body.splitlines():
            if not line.strip():
                continue
            match = re.fullmatch(r'\s*\("([a-z]+)", "([A-Za-z_]+)"\),\s*', line)
            if not match:
                raise ValueError('unrecognized script alias: ' + line)
            aliases[match[1]] = match[2]
        data['aliases'][kind] = aliases
    validate(data)
    return data


def render(data):
    lines = ['package regex4cj', '', '// Generated by scripts/generate_scripts.py; do not edit.',
             '// Unicode ' + VERSION + '; source revision ' + REV + '.',
             '// See data/unicode/LICENSE-UNICODE and THIRD_PARTY_NOTICES.md.']
    # A query probes Script only after general-category aliases are resolved.
    lines += ['func isScriptName(name: String): Bool {', '    match (name) {']
    for name in data['tables']['Script']:
        aliases = [k for k, v in data['aliases']['Script'].items() if v == name]
        lines.append('        case ' + ' | '.join('"' + a + '"' for a in aliases) + ' => return true')
    lines += ['        case _ => return false', '    }', '}', '']
    for kind in KINDS:
        lines += ['func unicode' + kind + '(name: String): CharSet {', '    match (name) {']
        for name in data['tables'][kind]:
            aliases = [k for k, v in data['aliases'][kind].items() if v == name]
            lines.append('        case ' + ' | '.join('"' + a + '"' for a in aliases) + ' => return ' + kind + name + '()')
        lines += ['        case _ => throw Exception("unknown Unicode script: " + name)', '    }', '}', '']
        for name, ranges in data['tables'][kind].items():
            lines += ['func ' + kind + name + '(): CharSet {', '    CharSet([']
            lines += ['        0x%X, 0x%X,' % (a, b) for a, b in ranges]
            lines += ['    ])', '}', '']
    return '\n'.join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--upstream', type=Path)
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    data = read_upstream(args.upstream) if args.upstream else json.loads(SNAPSHOT.read_text())
    validate(data)
    snapshot = json.dumps(data, ensure_ascii=False, indent=2) + '\n'
    output = render(data)
    if args.check:
        if args.upstream and SNAPSHOT.read_text() != snapshot:
            raise ValueError('snapshot differs from upstream')
        if OUTPUT.read_text() != output:
            raise ValueError('generated script table is stale')
    else:
        if args.upstream:
            SNAPSHOT.write_text(snapshot)
        OUTPUT.write_text(output)
    print('Unicode ' + VERSION + ' Script/Script_Extensions verified: 170 tables each')


if __name__ == '__main__':
    main()
