"""Import pinned Unicode simple case-folding pairs and regenerate the offline table."""
import argparse
import ast
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REV = '72d650cb0a880a01ab6dc2137c0888e8f89740f7'
VERSION = '16.0.0'
SNAPSHOT = ROOT / 'data/unicode/case_folding_simple.json'
OUTPUT = ROOT / 'port/src/case_fold.cj'
SOURCE = 'regex-syntax/src/unicode_tables/case_folding_simple.rs'
LITERAL = r"'(?:\\.|[^'\\])*'"


def rune(token):
    token = re.sub(r'\\u\{([0-9a-fA-F]+)\}', lambda m: '\\U' + format(int(m[1], 16), '08x'), token)
    value = ast.literal_eval(token)
    if len(value) != 1:
        raise ValueError('invalid Rust scalar literal: ' + token)
    return ord(value)


def validate(data):
    if data['revision'] != REV or data['unicode_version'] != VERSION:
        raise ValueError('unexpected version')
    if data['source'] != SOURCE:
        raise ValueError('unexpected source')
    last = -1
    seen = set()
    for key, folds in data['pairs']:
        if not (0 <= key <= 0x10FFFF) or key in seen or key <= last:
            raise ValueError('case fold keys must be increasing scalars')
        if 0xD800 <= key <= 0xDFFF:
            raise ValueError('surrogate case fold key')
        if not folds or key in folds or len(folds) != len(set(folds)):
            raise ValueError('invalid equivalence class for U+%04X' % key)
        for fold in folds:
            if not (0 <= fold <= 0x10FFFF) or 0xD800 <= fold <= 0xDFFF:
                raise ValueError('invalid case fold target')
        seen.add(key)
        last = key
    by_key = {key: set(folds) for key, folds in data['pairs']}
    # The pinned table stores full equivalence classes, not one-step maps.
    for key, folds in data['pairs']:
        group = set(folds) | {key}
        for other in folds:
            if other not in by_key or (set(by_key[other]) | {other}) != group:
                raise ValueError('case fold class is not symmetric at U+%04X' % key)
    samples = {
        ord('K'): {ord('k'), 0x212A},
        ord('σ'): {ord('Σ'), ord('ς')},
        ord('ß'): {ord('ẞ')},
    }
    for key, expected in samples.items():
        if set(by_key[key]) != expected:
            raise ValueError('unexpected sample folding for U+%04X' % key)


def read_upstream(path):
    if subprocess.check_output(['git', '-C', str(path), 'rev-parse', 'HEAD'], text=True).strip() != REV:
        raise ValueError('wrong upstream revision')
    raw = (path / SOURCE).read_bytes()
    committed = subprocess.check_output(['git', '-C', str(path), 'show', REV + ':' + SOURCE])
    if raw != committed:
        raise ValueError('modified upstream source')
    text = raw.decode()
    if 'Unicode version: ' + VERSION + '.' not in text:
        raise ValueError('wrong Unicode version')
    body = text.split('= &[', 1)[1].split('];', 1)[0]
    pairs = []
    row = re.compile(r"\s*\((" + LITERAL + r"), &\[((?:" + LITERAL + r"\s*,?\s*)*)\]\),\s*")
    item = re.compile(LITERAL)
    for line in body.splitlines():
        if not line.strip():
            continue
        match = row.fullmatch(line)
        if not match:
            raise ValueError('unrecognized case fold row: ' + line)
        folds = [rune(token) for token in item.findall(match[2])]
        pairs.append([rune(match[1]), folds])
    data = {
        'revision': REV,
        'unicode_version': VERSION,
        'source': SOURCE,
        'source_sha256': hashlib.sha256(raw).hexdigest(),
        'pairs': pairs,
    }
    validate(data)
    return data


def render(data):
    lines = [
        'package cjregex',
        '',
        '// Generated by scripts/generate_case_fold.py; do not edit.',
        '// Unicode ' + VERSION + '; source revision ' + REV + '.',
        '// See data/unicode/LICENSE-UNICODE and THIRD_PARTY_NOTICES.md.',
        '// Flat records are key, count, then the other members of the equivalence class.',
        'func caseFoldTable(): Array<Int64> {',
        '    return [',
    ]
    for key, folds in data['pairs']:
        parts = ['0x%X' % key, str(len(folds))] + ['0x%X' % fold for fold in folds]
        lines.append('        ' + ', '.join(parts) + ',')
    lines += ['    ]', '}', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--upstream', type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = read_upstream(args.upstream) if args.upstream else json.loads(SNAPSHOT.read_text())
    validate(data)
    snapshot = json.dumps(data, ensure_ascii=False, indent=2) + '\n'
    output = render(data)
    if args.check:
        if args.upstream and SNAPSHOT.read_text() != snapshot:
            raise ValueError('snapshot differs from upstream')
        if OUTPUT.read_text() != output:
            raise ValueError('generated case fold table is stale')
    else:
        if args.upstream:
            SNAPSHOT.write_text(snapshot)
        OUTPUT.write_text(output)
    print('Unicode ' + VERSION + ' simple case folding verified: ' + str(len(data['pairs'])) + ' scalars')


if __name__ == '__main__':
    main()
